"""Station metadata used by forecasts and market filtering."""

from __future__ import annotations


STATIONS = {
    "KLGA": {
        "name": "LaGuardia Airport, NY",
        "market_label": "NYC",
        "icao": "KLGA",
        "resolution_unit": "F",
        "lat": 40.7772,
        "lon": -73.8726,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ny/new-york-city/KLGA",
        "iem_network": "NY_ASOS",
        "iem_station": "LGA",
        "nws_grid_office": "OKX",
        "nws_grid_x": 33,
        "nws_grid_y": 37,
        "priority": "HIGH",
        "city_slug": "nyc",
        # Backtested: 363 days, 44.1% bucket accuracy (exhaustive 5-model search)
        "ensemble_models": [
            "ncep_nbm_conus",
            "gfs_graphcast025",
            "icon_seamless",
            "kma_seamless",
            "gem_seamless",
            "kma_gdps",
            "gem_hrdps_continental",
            "ncep_aigfs025"
        ],
        "spread_threshold": 3.0,   # °F — range-bucket city
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 363,
    },
    "KORD": {
        "name": "Chicago O'Hare",
        "market_label": "Chicago",
        "icao": "KORD",
        "resolution_unit": "F",
        "lat": 41.9742,
        "lon": -87.9073,
        "timezone": "America/Chicago",
        "station_standard_offset_hours": -6,
        "wu_url": "https://www.wunderground.com/history/daily/us/il/chicago/KORD",
        "iem_network": "IL_ASOS",
        "iem_station": "ORD",
        "nws_grid_office": "LOT",
        "nws_grid_x": 75,
        "nws_grid_y": 72,
        "priority": "HIGH",
        "city_slug": "chicago",
        # Backtested: 32 days, 71.9% bucket accuracy (5-model ensemble)
        "ensemble_models": [
            "ncep_nbm_conus",
            "ncep_aigfs025",
            "gem_seamless",
            "best_match",
            "icon_seamless",
            "ecmwf_ifs025",
            "gfs_seamless"
        ],
        "spread_threshold": 3.0,   # °F
        "p_win_green": 0.65,
        "p_win_red": 0.55,
        "kelly_fraction": 0.25,
        "backtest_n": 32,
    },
    "KDEN": {
        "name": "Denver International",
        "market_label": "Denver",
        "icao": "KDEN",
        "resolution_unit": "F",
        "lat": 39.8561,
        "lon": -104.6737,
        "timezone": "America/Denver",
        "station_standard_offset_hours": -7,
        "wu_url": "https://www.wunderground.com/history/daily/us/co/denver/KDEN",
        "iem_network": "CO_ASOS",
        "iem_station": "DEN",
        "nws_grid_office": "BOU",
        "nws_grid_x": 62,
        "nws_grid_y": 60,
        "priority": "HIGH",
        "city_slug": "denver",
        "paused": True,
        "ensemble_models": ["ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025", "icon_seamless"],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KBOS": {
        "name": "Boston Logan",
        "market_label": "Boston",
        "icao": "KBOS",
        "resolution_unit": "F",
        "lat": 42.3656,
        "lon": -71.0096,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ma/boston/KBOS",
        "iem_network": "MA_ASOS",
        "iem_station": "BOS",
        "nws_grid_office": "BOX",
        "nws_grid_x": 71,
        "nws_grid_y": 90,
        "priority": "HIGH",
        "city_slug": "boston",
        "paused": True,
        "ensemble_models": ["ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025", "icon_seamless"],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KMIA": {
        "name": "Miami International",
        "market_label": "Miami",
        "icao": "KMIA",
        "resolution_unit": "F",
        "lat": 25.7959,
        "lon": -80.2870,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/fl/miami/KMIA",
        "iem_network": "FL_ASOS",
        "iem_station": "MIA",
        "nws_grid_office": "MFL",
        "nws_grid_x": 75,
        "nws_grid_y": 51,
        "priority": "MEDIUM",
        "city_slug": "miami",
        "ensemble_models": [
            "gem_global",
            "ncep_aigfs025",
            "gem_seamless",
            "gem_regional",
            "gfs_graphcast025",
            "ncep_nbm_conus",
            "ecmwf_ifs025",
            "gfs_seamless",
            "icon_seamless"
        ],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KSEA": {
        "name": "Seattle-Tacoma",
        "market_label": "Seattle",
        "icao": "KSEA",
        "resolution_unit": "F",
        "lat": 47.4502,
        "lon": -122.3088,
        "timezone": "America/Los_Angeles",
        "station_standard_offset_hours": -8,
        "wu_url": "https://www.wunderground.com/history/daily/us/wa/seattle/KSEA",
        "iem_network": "WA_ASOS",
        "iem_station": "SEA",
        "nws_grid_office": "SEW",
        "nws_grid_x": 124,
        "nws_grid_y": 67,
        "priority": "MEDIUM",
        "city_slug": "seattle",
        # Backtested: 81 days, best ensemble: ICON + GEM + NBM
        "ensemble_models": [
            "ncep_nbm_conus",
            "gem_seamless",
            "gem_hrdps_continental",
            "knmi_seamless",
            "dmi_seamless",
            "icon_seamless",
            "ecmwf_ifs025",
            "gfs_seamless"
        ],
        "spread_threshold": 3.0,   # °F
        "p_win_green": 0.62,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 81,
    },
    "KDFW": {
        "name": "Dallas/Fort Worth",
        "market_label": "Dallas",
        "icao": "KDFW",
        "resolution_unit": "F",
        "lat": 32.8998,
        "lon": -97.0403,
        "timezone": "America/Chicago",
        "station_standard_offset_hours": -6,
        "wu_url": "https://www.wunderground.com/history/daily/us/tx/dallas/KDFW",
        "iem_network": "TX_ASOS",
        "iem_station": "DFW",
        "nws_grid_office": "FWD",
        "nws_grid_x": 80,
        "nws_grid_y": 108,
        "priority": "MEDIUM",
        "city_slug": "dallas",
        "ensemble_models": [
            "icon_seamless",
            "gem_seamless",
            "gem_regional",
            "gfs_seamless",
            "gfs_hrrr",
            "ncep_aigfs025",
            "ecmwf_ifs025",
            "ncep_nbm_conus"
        ],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KATL": {
        "name": "Atlanta Hartsfield-Jackson",
        "market_label": "Atlanta",
        "icao": "KATL",
        "resolution_unit": "F",
        "lat": 33.6407,
        "lon": -84.4277,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ga/atlanta/KATL",
        "iem_network": "GA_ASOS",
        "iem_station": "ATL",
        "nws_grid_office": "FFC",
        "nws_grid_x": 52,
        "nws_grid_y": 88,
        "priority": "MEDIUM",
        "city_slug": "atlanta",
        "ensemble_models": [
            "ncep_nbm_conus",
            "icon_seamless",
            "gem_global",
            "ncep_aigfs025",
            "gem_seamless",
            "ecmwf_ifs025",
            "gfs_seamless"
        ],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "EGLC": {
        "name": "London City Airport",
        "market_label": "London",
        "icao": "EGLC",
        "resolution_unit": "C",
        "lat": 51.5054,
        "lon": 0.0553,
        "timezone": "Europe/London",
        "station_standard_offset_hours": 0,
        "wu_url": "https://www.wunderground.com/history/daily/gb/london/EGLC",
        "iem_network": "GB__ASOS",
        "iem_station": "EGLC",
        "met_office_lat": 51.5054,
        "met_office_lon": 0.0553,
        "priority": "MEDIUM",
        "city_slug": "london",
        # Backtested: 75 days, 74.7% bucket accuracy. Spread signal p=0.039.
        # GREEN (≤1.0°C spread): 80.8% (42/52). RED (>1.0°C): 47.6% (10/21).
        "ensemble_models": [
            "meteofrance_arome_france",
            "meteofrance_seamless",
            "meteofrance_arome_france_hd",
            "icon_seamless",
            "dmi_seamless",
            "ecmwf_ifs025",
            "kma_seamless",
            "ukmo_uk_deterministic_2km",
            "ukmo_seamless",
            "ukmo_global_deterministic_10km",
            "ncep_aigfs025"
        ],
        "spread_threshold": 1.0,   # °C — pre-registered, do not change
        "p_win_green": 0.75,       # validated empirical
        "p_win_red": 0.55,         # shrunk toward base rate
        "kelly_fraction": 0.50,    # half-Kelly — 75 days of backtest IS the validation
        "backtest_n": 75,
    },
    "LFPG": {
        "name": "Paris Charles de Gaulle",
        "market_label": "Paris",
        "icao": "LFPG",
        "resolution_unit": "C",
        "lat": 49.0097,
        "lon": 2.5479,
        "timezone": "Europe/Paris",
        "station_standard_offset_hours": 1,
        "wu_url": "https://www.wunderground.com/history/daily/fr/paris/LFPG",
        "iem_network": "FR__ASOS",
        "iem_station": "LFPG",
        "priority": "LOW",
        "city_slug": "paris",
        # Backtested: 10 days only — small sample, use conservatively
        "ensemble_models": [
            "ukmo_seamless",
            "ukmo_uk_deterministic_2km",
            "metno_seamless",
            "ecmwf_ifs025",
            "meteofrance_seamless",
            "jma_seamless",
            "ncep_aigfs025",
            "meteofrance_arome_france",
            "icon_seamless",
            "dmi_seamless"
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.65,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 10,
    },
    "RKSI": {
        "name": "Incheon International Airport",
        "market_label": "Seoul",
        "icao": "RKSI",
        "resolution_unit": "C",
        "lat": 37.4492,
        "lon": 126.4510,
        "timezone": "Asia/Seoul",
        "station_standard_offset_hours": 9,
        "wu_url": "https://www.wunderground.com/history/daily/kr/incheon/RKSI",
        "iem_network": "KR__ASOS",
        "iem_station": "RKSI",
        "priority": "LOW",
        "city_slug": "seoul",
        # Backtested: ~50 days, NCEP AI-GFS + GraphCast best combination
        "ensemble_models": [
            "ncep_aigfs025",
            "gfs_graphcast025",
            "ecmwf_ifs025",
            "ncep_hgefs025_ensemble_mean",
            "kma_gdps",
            "kma_seamless",
            "icon_seamless",
            "meteofrance_seamless"
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.70,
        "p_win_red": 0.55,
        "kelly_fraction": 0.35,
        "backtest_n": 50,
    },
    "SBGR": {
        "name": "Sao Paulo-Guarulhos International Airport",
        "market_label": "Sao Paulo",
        "icao": "SBGR",
        "resolution_unit": "C",
        "lat": -23.4356,
        "lon": -46.4731,
        "timezone": "America/Sao_Paulo",
        "station_standard_offset_hours": -3,
        "wu_url": "https://www.wunderground.com/history/daily/br/guarulhos/SBGR",
        "iem_network": "BR__ASOS",
        "iem_station": "SBGR",
        "priority": "LOW",
        "city_slug": "sao-paulo",
        "paused": True,
        "ensemble_models": ["ecmwf_ifs025", "gem_global", "icon_seamless", "gfs_seamless"],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "SAEZ": {
        "name": "Buenos Aires Ezeiza International Airport",
        "market_label": "Buenos Aires",
        "icao": "SAEZ",
        "resolution_unit": "C",
        "lat": -34.8222,
        "lon": -58.5358,
        "timezone": "America/Argentina/Buenos_Aires",
        "station_standard_offset_hours": -3,
        "wu_url": "https://www.wunderground.com/history/daily/ar/buenos-aires/SAEZ",
        "iem_network": "AR__ASOS",
        "iem_station": "SAEZ",
        "priority": "LOW",
        "city_slug": "buenos-aires",
        # Backtested: 78 days, UKMO Seamless 65.4% — UK Met Office excels in Southern Hemisphere.
        # No ensemble beats single UKMO; use ECMWF + ICON for spread signal.
        "ensemble_models": [
            "ukmo_seamless",
            "ecmwf_ifs025",
            "best_match",
            "icon_seamless",
            "ncep_aigfs025",
            "meteofrance_seamless",
            "gfs_seamless"
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.65,
        "p_win_red": 0.55,
        "kelly_fraction": 0.30,
        "backtest_n": 78,
    },
    "NZWN": {
        "name": "Wellington International Airport",
        "market_label": "Wellington",
        "icao": "NZWN",
        "resolution_unit": "C",
        "lat": -41.3272,
        "lon": 174.8050,
        "timezone": "Pacific/Auckland",
        "station_standard_offset_hours": 12,
        "wu_url": "https://www.wunderground.com/history/daily/nz/wellington/NZWN",
        "iem_network": "NF__ASOS",
        "iem_station": "NZWN",
        "priority": "LOW",
        "city_slug": "wellington",
        # Not yet backtested — BOM ACCESS-G best for NZ, UKMO excellent for SH.
        # Add ecmwf + icon for spread diversity.
        "ensemble_models": [
            "bom_access_global",
            "ukmo_seamless",
            "ecmwf_ifs025",
            "icon_seamless",
            "gfs_seamless"
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.60,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "LTAC": {
        "name": "Ankara Esenboğa International Airport",
        "market_label": "Ankara",
        "icao": "LTAC",
        "resolution_unit": "C",
        "lat": 40.1281,
        "lon": 32.9951,
        "timezone": "Europe/Istanbul",
        "station_standard_offset_hours": 3,
        "wu_url": "https://www.wunderground.com/history/daily/tr/%C3%A7ubuk/LTAC",
        "iem_network": "TR__ASOS",
        "iem_station": "LTAC",
        "priority": "LOW",
        "city_slug": "ankara",
        # Backtested: 37 days, 62.2% bucket accuracy (+16.3pp over best single)
        "ensemble_models": [
            "icon_seamless",
            "icon_global",
            "ecmwf_ifs025",
            "gfs_graphcast025",
            "jma_seamless",
            "meteofrance_arpege_world"
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.70,
        "p_win_red": 0.55,
        "kelly_fraction": 0.35,
        "backtest_n": 37,
    },
    "CYYZ": {
        "name": "Toronto Pearson International Airport",
        "market_label": "Toronto",
        "icao": "CYYZ",
        "resolution_unit": "C",
        "lat": 43.6772,
        "lon": -79.6306,
        "timezone": "America/Toronto",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/ca/toronto/CYYZ",
        "iem_network": "CA_ON_ASOS",
        "iem_station": "CYYZ",
        "priority": "LOW",
        "city_slug": "toronto",
        # Backtested: 81 days, 53.1% bucket accuracy (KMA + MF ARPEGE + GEM + DMI)
        "ensemble_models": [
            "ncep_nbm_conus",
            "kma_gdps",
            "meteofrance_arpege_world",
            "gem_global",
            "dmi_seamless",
            "ncep_aigfs025",
            "gem_regional",
            "gfs_seamless",
            "ecmwf_ifs025"
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.65,
        "p_win_red": 0.55,
        "kelly_fraction": 0.25,
        "backtest_n": 81,
    },
    # ── New cities (Phase 1 — starter ensembles, no backtest yet) ─────────
    "KSFO": {
        "name": "San Francisco International",
        "market_label": "San Francisco",
        "icao": "KSFO",
        "resolution_unit": "F",
        "lat": 37.6213,
        "lon": -122.3790,
        "timezone": "America/Los_Angeles",
        "station_standard_offset_hours": -8,
        "wu_url": "https://www.wunderground.com/history/daily/us/ca/san-francisco/KSFO",
        "iem_network": "CA_ASOS",
        "iem_station": "SFO",
        "priority": "LOW",
        "city_slug": "san-francisco",
        "paused": True,
        "ensemble_models": [
            "ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025",
            "icon_seamless", "gem_seamless", "ncep_aigfs025",
            "gfs_graphcast025", "gfs_hrrr",
        ],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KLAX": {
        "name": "Los Angeles International",
        "market_label": "Los Angeles",
        "icao": "KLAX",
        "resolution_unit": "F",
        "lat": 33.9425,
        "lon": -118.4081,
        "timezone": "America/Los_Angeles",
        "station_standard_offset_hours": -8,
        "wu_url": "https://www.wunderground.com/history/daily/us/ca/los-angeles/KLAX",
        "iem_network": "CA_ASOS",
        "iem_station": "LAX",
        "priority": "LOW",
        "city_slug": "los-angeles",
        "paused": True,
        "ensemble_models": [
            "ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025",
            "icon_seamless", "gem_seamless", "ncep_aigfs025",
            "gfs_graphcast025", "gfs_hrrr",
        ],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KIAH": {
        "name": "Houston George Bush Intercontinental",
        "market_label": "Houston",
        "icao": "KIAH",
        "resolution_unit": "F",
        "lat": 29.9844,
        "lon": -95.3414,
        "timezone": "America/Chicago",
        "station_standard_offset_hours": -6,
        "wu_url": "https://www.wunderground.com/history/daily/us/tx/houston/KIAH",
        "iem_network": "TX_ASOS",
        "iem_station": "IAH",
        "priority": "LOW",
        "city_slug": "houston",
        "paused": True,
        "ensemble_models": [
            "ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025",
            "icon_seamless", "gem_seamless", "ncep_aigfs025",
            "gfs_graphcast025", "gfs_hrrr",
        ],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KAUS": {
        "name": "Austin-Bergstrom International",
        "market_label": "Austin",
        "icao": "KAUS",
        "resolution_unit": "F",
        "lat": 30.1945,
        "lon": -97.6699,
        "timezone": "America/Chicago",
        "station_standard_offset_hours": -6,
        "wu_url": "https://www.wunderground.com/history/daily/us/tx/austin/KAUS",
        "iem_network": "TX_ASOS",
        "iem_station": "AUS",
        "priority": "LOW",
        "city_slug": "austin",
        "paused": True,
        "ensemble_models": [
            "ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025",
            "icon_seamless", "gem_seamless", "ncep_aigfs025",
            "gfs_graphcast025", "gfs_hrrr",
        ],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "EPWA": {
        "name": "Warsaw Chopin",
        "market_label": "Warsaw",
        "icao": "EPWA",
        "resolution_unit": "C",
        "lat": 52.1657,
        "lon": 20.9671,
        "timezone": "Europe/Warsaw",
        "station_standard_offset_hours": 1,
        "wu_url": "https://www.wunderground.com/history/daily/pl/warsaw/EPWA",
        "iem_network": "PL__ASOS",
        "iem_station": "EPWA",
        "priority": "LOW",
        "city_slug": "warsaw",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "dmi_seamless",
            "meteofrance_seamless", "ukmo_seamless", "ncep_aigfs025",
            "gfs_seamless", "knmi_seamless",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "EDDM": {
        "name": "Munich Airport",
        "market_label": "Munich",
        "icao": "EDDM",
        "resolution_unit": "C",
        "lat": 48.3537,
        "lon": 11.7860,
        "timezone": "Europe/Berlin",
        "station_standard_offset_hours": 1,
        "wu_url": "https://www.wunderground.com/history/daily/de/munich/EDDM",
        "iem_network": "DE__ASOS",
        "iem_station": "EDDM",
        "priority": "LOW",
        "city_slug": "munich",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "icon_eu",
            "dmi_seamless", "meteofrance_seamless", "ukmo_seamless",
            "ncep_aigfs025", "knmi_seamless",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "LEMD": {
        "name": "Madrid Barajas",
        "market_label": "Madrid",
        "icao": "LEMD",
        "resolution_unit": "C",
        "lat": 40.4719,
        "lon": -3.5626,
        "timezone": "Europe/Madrid",
        "station_standard_offset_hours": 1,
        "wu_url": "https://www.wunderground.com/history/daily/es/madrid/LEMD",
        "iem_network": "ES__ASOS",
        "iem_station": "LEMD",
        "priority": "LOW",
        "city_slug": "madrid",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "meteofrance_seamless",
            "meteofrance_arpege_world", "ukmo_seamless", "ncep_aigfs025",
            "gfs_seamless", "dmi_seamless",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "LIMC": {
        "name": "Milan Malpensa",
        "market_label": "Milan",
        "icao": "LIMC",
        "resolution_unit": "C",
        "lat": 45.6306,
        "lon": 8.7231,
        "timezone": "Europe/Rome",
        "station_standard_offset_hours": 1,
        "wu_url": "https://www.wunderground.com/history/daily/it/milan/LIMC",
        "iem_network": "IT__ASOS",
        "iem_station": "LIMC",
        "priority": "LOW",
        "city_slug": "milan",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "icon_eu",
            "meteofrance_seamless", "meteofrance_arome_france",
            "ukmo_seamless", "ncep_aigfs025", "dmi_seamless",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "LLBG": {
        "name": "Tel Aviv Ben Gurion",
        "market_label": "Tel Aviv",
        "icao": "LLBG",
        "resolution_unit": "C",
        "lat": 32.0114,
        "lon": 34.8867,
        "timezone": "Asia/Jerusalem",
        "station_standard_offset_hours": 2,
        "wu_url": "https://www.wunderground.com/history/daily/il/tel-aviv/LLBG",
        "iem_network": "IL__ASOS",
        "iem_station": "LLBG",
        "priority": "LOW",
        "city_slug": "tel-aviv",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "icon_global",
            "gfs_seamless", "meteofrance_arpege_world",
            "ncep_aigfs025", "jma_seamless",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "RJTT": {
        "name": "Tokyo Haneda",
        "market_label": "Tokyo",
        "icao": "RJTT",
        "resolution_unit": "C",
        "lat": 35.5494,
        "lon": 139.7798,
        "timezone": "Asia/Tokyo",
        "station_standard_offset_hours": 9,
        "wu_url": "https://www.wunderground.com/history/daily/jp/tokyo/RJTT",
        "iem_network": "JP__ASOS",
        "iem_station": "RJTT",
        "priority": "LOW",
        "city_slug": "tokyo",
        "paused": True,
        "ensemble_models": [
            "jma_seamless", "jma_gsm", "ecmwf_ifs025",
            "icon_seamless", "kma_seamless", "ncep_aigfs025",
            "gfs_seamless", "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "ZSPD": {
        "name": "Shanghai Pudong",
        "market_label": "Shanghai",
        "icao": "ZSPD",
        "resolution_unit": "C",
        "lat": 31.1434,
        "lon": 121.8052,
        "timezone": "Asia/Shanghai",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/cn/shanghai/ZSPD",
        "iem_network": "CN__ASOS",
        "iem_station": "ZSPD",
        "priority": "LOW",
        "city_slug": "shanghai",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "kma_seamless", "cma_grapes_global", "ncep_aigfs025",
            "gfs_seamless", "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "ZBAA": {
        "name": "Beijing Capital",
        "market_label": "Beijing",
        "icao": "ZBAA",
        "resolution_unit": "C",
        "lat": 40.0799,
        "lon": 116.6031,
        "timezone": "Asia/Shanghai",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/cn/beijing/ZBAA",
        "iem_network": "CN__ASOS",
        "iem_station": "ZBAA",
        "priority": "LOW",
        "city_slug": "beijing",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "kma_seamless", "cma_grapes_global", "ncep_aigfs025",
            "gfs_seamless", "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "VHHH": {
        "name": "Hong Kong International",
        "market_label": "Hong Kong",
        "icao": "VHHH",
        "resolution_unit": "C",
        "lat": 22.3080,
        "lon": 113.9185,
        "timezone": "Asia/Hong_Kong",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/hk/hong-kong/VHHH",
        "iem_network": "HK__ASOS",
        "iem_station": "VHHH",
        "priority": "LOW",
        "city_slug": "hong-kong",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "kma_seamless", "ncep_aigfs025", "gfs_seamless",
            "gfs_graphcast025", "bom_access_global",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "RCTP": {
        "name": "Taipei Taoyuan",
        "market_label": "Taipei",
        "icao": "RCTP",
        "resolution_unit": "C",
        "lat": 25.0777,
        "lon": 121.2325,
        "timezone": "Asia/Taipei",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/tw/taipei/RCTP",
        "iem_network": "TW__ASOS",
        "iem_station": "RCTP",
        "priority": "LOW",
        "city_slug": "taipei",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "kma_seamless", "ncep_aigfs025", "gfs_seamless",
            "gfs_graphcast025", "cma_grapes_global",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "WSSS": {
        "name": "Singapore Changi",
        "market_label": "Singapore",
        "icao": "WSSS",
        "resolution_unit": "C",
        "lat": 1.3502,
        "lon": 103.9940,
        "timezone": "Asia/Singapore",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/sg/singapore/WSSS",
        "iem_network": "SG__ASOS",
        "iem_station": "WSSS",
        "priority": "LOW",
        "city_slug": "singapore",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "kma_seamless", "ncep_aigfs025", "gfs_seamless",
            "gfs_graphcast025", "bom_access_global",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "ZUCK": {
        "name": "Chongqing Jiangbei",
        "market_label": "Chongqing",
        "icao": "ZUCK",
        "resolution_unit": "C",
        "lat": 29.7192,
        "lon": 106.6413,
        "timezone": "Asia/Shanghai",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/cn/chongqing/ZUCK",
        "iem_network": "CN__ASOS",
        "iem_station": "ZUCK",
        "priority": "LOW",
        "city_slug": "chongqing",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "cma_grapes_global", "ncep_aigfs025", "gfs_seamless",
            "kma_seamless", "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "ZUUU": {
        "name": "Chengdu Shuangliu",
        "market_label": "Chengdu",
        "icao": "ZUUU",
        "resolution_unit": "C",
        "lat": 30.5785,
        "lon": 103.9471,
        "timezone": "Asia/Shanghai",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/cn/chengdu/ZUUU",
        "iem_network": "CN__ASOS",
        "iem_station": "ZUUU",
        "priority": "LOW",
        "city_slug": "chengdu",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "cma_grapes_global", "ncep_aigfs025", "gfs_seamless",
            "kma_seamless", "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "ZHHH": {
        "name": "Wuhan Tianhe",
        "market_label": "Wuhan",
        "icao": "ZHHH",
        "resolution_unit": "C",
        "lat": 30.7838,
        "lon": 114.2081,
        "timezone": "Asia/Shanghai",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/cn/wuhan/ZHHH",
        "iem_network": "CN__ASOS",
        "iem_station": "ZHHH",
        "priority": "LOW",
        "city_slug": "wuhan",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "cma_grapes_global", "ncep_aigfs025", "gfs_seamless",
            "kma_seamless", "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "ZGSZ": {
        "name": "Shenzhen Bao'an",
        "market_label": "Shenzhen",
        "icao": "ZGSZ",
        "resolution_unit": "C",
        "lat": 22.6393,
        "lon": 113.8107,
        "timezone": "Asia/Shanghai",
        "station_standard_offset_hours": 8,
        "wu_url": "https://www.wunderground.com/history/daily/cn/shenzhen/ZGSZ",
        "iem_network": "CN__ASOS",
        "iem_station": "ZGSZ",
        "priority": "LOW",
        "city_slug": "shenzhen",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "jma_seamless",
            "kma_seamless", "cma_grapes_global", "ncep_aigfs025",
            "gfs_seamless", "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "VILK": {
        "name": "Lucknow Chaudhary Charan Singh",
        "market_label": "Lucknow",
        "icao": "VILK",
        "resolution_unit": "C",
        "lat": 26.7606,
        "lon": 80.8893,
        "timezone": "Asia/Kolkata",
        "station_standard_offset_hours": 5,
        "wu_url": "https://www.wunderground.com/history/daily/in/lucknow/VILK",
        "iem_network": "IN__ASOS",
        "iem_station": "VILK",
        "priority": "LOW",
        "city_slug": "lucknow",
        "paused": True,
        "ensemble_models": [
            "ecmwf_ifs025", "icon_seamless", "icon_global",
            "gfs_seamless", "jma_seamless", "ncep_aigfs025",
            "meteofrance_arpege_world", "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
}


MARKET_KEYWORDS_TO_STATION = {
    "nyc": "KLGA",
    "new york city": "KLGA",
    "chicago": "KORD",
    "denver": "KDEN",
    "boston": "KBOS",
    "london": "EGLC",
    "paris": "LFPG",
    "miami": "KMIA",
    "seattle": "KSEA",
    "atlanta": "KATL",
    "dallas": "KDFW",
    "seoul": "RKSI",
    "incheon": "RKSI",
    "sao paulo": "SBGR",
    "sao-paulo": "SBGR",
    "guarulhos": "SBGR",
    "sbgr": "SBGR",
}


_DASHBOARD_CITY_ALIASES: dict[str, str] = {
    "NYC": "New York",
}


def canonical_dashboard_city(city: str) -> str:
    """Normalize a city label to the canonical key used by the accuracy dashboard.

    The trading pipeline uses market_label (e.g. "NYC") but the accuracy
    pipeline, React dashboard config, and all cached data files historically
    use "New York".  This helper bridges the gap.
    """
    return _DASHBOARD_CITY_ALIASES.get(city, city)


def find_station_for_question(question: str) -> str | None:
    lower = question.lower()
    for keyword, station in MARKET_KEYWORDS_TO_STATION.items():
        if keyword in lower:
            return station
    return None
