"""Station metadata used by forecasts and market filtering."""

from __future__ import annotations


STATIONS = {
    "KLGA": {
        "name": "LaGuardia Airport, NY",
        "market_label": "NYC",
        "icao": "KLGA",
        "resolution_unit": "F",
        "lat": 40.7772,
        "lon": -73.8726,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ny/new-york-city/KLGA",
        "nws_grid_office": "OKX",
        "nws_grid_x": 33,
        "nws_grid_y": 37,
        "priority": "HIGH",
        "city_slug": "nyc",
    },
    "KORD": {
        "name": "Chicago O'Hare",
        "market_label": "Chicago",
        "icao": "KORD",
        "resolution_unit": "F",
        "lat": 41.9742,
        "lon": -87.9073,
        "timezone": "America/Chicago",
        "station_standard_offset_hours": -6,
        "wu_url": "https://www.wunderground.com/history/daily/us/il/chicago/KORD",
        "nws_grid_office": "LOT",
        "nws_grid_x": 75,
        "nws_grid_y": 72,
        "priority": "HIGH",
        "city_slug": "chicago",
    },
    "KDEN": {
        "name": "Denver International",
        "market_label": "Denver",
        "icao": "KDEN",
        "resolution_unit": "F",
        "lat": 39.8561,
        "lon": -104.6737,
        "timezone": "America/Denver",
        "station_standard_offset_hours": -7,
        "wu_url": "https://www.wunderground.com/history/daily/us/co/denver/KDEN",
        "nws_grid_office": "BOU",
        "nws_grid_x": 62,
        "nws_grid_y": 60,
        "priority": "HIGH",
        "city_slug": "denver",
    },
    "KBOS": {
        "name": "Boston Logan",
        "market_label": "Boston",
        "icao": "KBOS",
        "resolution_unit": "F",
        "lat": 42.3656,
        "lon": -71.0096,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ma/boston/KBOS",
        "nws_grid_office": "BOX",
        "nws_grid_x": 71,
        "nws_grid_y": 90,
        "priority": "HIGH",
        "city_slug": "boston",
    },
    "KMIA": {
        "name": "Miami International",
        "market_label": "Miami",
        "icao": "KMIA",
        "resolution_unit": "F",
        "lat": 25.7959,
        "lon": -80.2870,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/fl/miami/KMIA",
        "nws_grid_office": "MFL",
        "nws_grid_x": 75,
        "nws_grid_y": 51,
        "priority": "MEDIUM",
        "city_slug": "miami",
    },
    "KSEA": {
        "name": "Seattle-Tacoma",
        "market_label": "Seattle",
        "icao": "KSEA",
        "resolution_unit": "F",
        "lat": 47.4502,
        "lon": -122.3088,
        "timezone": "America/Los_Angeles",
        "station_standard_offset_hours": -8,
        "wu_url": "https://www.wunderground.com/history/daily/us/wa/seattle/KSEA",
        "nws_grid_office": "SEW",
        "nws_grid_x": 124,
        "nws_grid_y": 67,
        "priority": "MEDIUM",
        "city_slug": "seattle",
    },
    "KDFW": {
        "name": "Dallas/Fort Worth",
        "market_label": "Dallas",
        "icao": "KDFW",
        "resolution_unit": "F",
        "lat": 32.8998,
        "lon": -97.0403,
        "timezone": "America/Chicago",
        "station_standard_offset_hours": -6,
        "wu_url": "https://www.wunderground.com/history/daily/us/tx/dallas/KDFW",
        "nws_grid_office": "FWD",
        "nws_grid_x": 80,
        "nws_grid_y": 108,
        "priority": "MEDIUM",
        "city_slug": "dallas",
    },
    "KATL": {
        "name": "Atlanta Hartsfield-Jackson",
        "market_label": "Atlanta",
        "icao": "KATL",
        "resolution_unit": "F",
        "lat": 33.6407,
        "lon": -84.4277,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ga/atlanta/KATL",
        "nws_grid_office": "FFC",
        "nws_grid_x": 52,
        "nws_grid_y": 88,
        "priority": "MEDIUM",
        "city_slug": "atlanta",
    },
    "EGLC": {
        "name": "London City Airport",
        "market_label": "London",
        "icao": "EGLC",
        "resolution_unit": "C",
        "lat": 51.5054,
        "lon": 0.0553,
        "timezone": "Europe/London",
        "station_standard_offset_hours": 0,
        "wu_url": "https://www.wunderground.com/history/daily/gb/london/EGLC",
        "met_office_lat": 51.5054,
        "met_office_lon": 0.0553,
        "priority": "MEDIUM",
        "city_slug": "london",
    },
    "LFPG": {
        "name": "Paris Charles de Gaulle",
        "market_label": "Paris",
        "icao": "LFPG",
        "resolution_unit": "C",
        "lat": 49.0097,
        "lon": 2.5479,
        "timezone": "Europe/Paris",
        "station_standard_offset_hours": 1,
        "wu_url": "https://www.wunderground.com/history/daily/fr/paris/LFPG",
        "priority": "LOW",
        "city_slug": "paris",
    },
    "RKSI": {
        "name": "Incheon International Airport",
        "market_label": "Seoul",
        "icao": "RKSI",
        "resolution_unit": "C",
        "lat": 37.4691,
        "lon": 126.4510,
        "timezone": "Asia/Seoul",
        "station_standard_offset_hours": 9,
        "wu_url": "https://www.wunderground.com/history/daily/kr/incheon/RKSI",
        "priority": "LOW",
        "city_slug": "seoul",
    },
    "SBGR": {
        "name": "Sao Paulo-Guarulhos International Airport",
        "market_label": "Sao Paulo",
        "icao": "SBGR",
        "resolution_unit": "C",
        "lat": -23.4356,
        "lon": -46.4731,
        "timezone": "America/Sao_Paulo",
        "station_standard_offset_hours": -3,
        "wu_url": "https://www.wunderground.com/history/daily/br/guarulhos/SBGR",
        "priority": "LOW",
        "city_slug": "sao-paulo",
    },
}


MARKET_KEYWORDS_TO_STATION = {
    "nyc": "KLGA",
    "new york city": "KLGA",
    "chicago": "KORD",
    "denver": "KDEN",
    "boston": "KBOS",
    "london": "EGLC",
    "paris": "LFPG",
    "miami": "KMIA",
    "seattle": "KSEA",
    "atlanta": "KATL",
    "dallas": "KDFW",
    "seoul": "RKSI",
    "incheon": "RKSI",
    "sao paulo": "SBGR",
    "sao-paulo": "SBGR",
    "guarulhos": "SBGR",
    "sbgr": "SBGR",
}


def find_station_for_question(question: str) -> str | None:
    lower = question.lower()
    for keyword, station in MARKET_KEYWORDS_TO_STATION.items():
        if keyword in lower:
            return station
    return None
