"""Station metadata used by forecasts and market filtering."""

from __future__ import annotations


STATIONS = {
    "KLGA": {
        "name": "LaGuardia Airport, NY",
        "market_label": "NYC",
        "icao": "KLGA",
        "resolution_unit": "F",
        "lat": 40.7772,
        "lon": -73.8726,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ny/new-york-city/KLGA",
        "nws_grid_office": "OKX",
        "nws_grid_x": 33,
        "nws_grid_y": 37,
        "priority": "HIGH",
        "city_slug": "nyc",
        # Backtested: 363 days, 44.1% bucket accuracy (exhaustive 5-model search)
        "ensemble_models": ["ncep_nbm_conus", "icon_seamless", "gfs_graphcast025", "kma_seamless", "gem_seamless"],
        "spread_threshold": 3.0,   # °F — range-bucket city
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 363,
    },
    "KORD": {
        "name": "Chicago O'Hare",
        "market_label": "Chicago",
        "icao": "KORD",
        "resolution_unit": "F",
        "lat": 41.9742,
        "lon": -87.9073,
        "timezone": "America/Chicago",
        "station_standard_offset_hours": -6,
        "wu_url": "https://www.wunderground.com/history/daily/us/il/chicago/KORD",
        "nws_grid_office": "LOT",
        "nws_grid_x": 75,
        "nws_grid_y": 72,
        "priority": "HIGH",
        "city_slug": "chicago",
        # Backtested: 32 days, 71.9% bucket accuracy (5-model ensemble)
        "ensemble_models": ["ncep_nbm_conus", "ncep_aigfs025", "gem_seamless", "best_match", "icon_seamless"],
        "spread_threshold": 3.0,   # °F
        "p_win_green": 0.65,
        "p_win_red": 0.55,
        "kelly_fraction": 0.25,
        "backtest_n": 32,
    },
    "KDEN": {
        "name": "Denver International",
        "market_label": "Denver",
        "icao": "KDEN",
        "resolution_unit": "F",
        "lat": 39.8561,
        "lon": -104.6737,
        "timezone": "America/Denver",
        "station_standard_offset_hours": -7,
        "wu_url": "https://www.wunderground.com/history/daily/us/co/denver/KDEN",
        "nws_grid_office": "BOU",
        "nws_grid_x": 62,
        "nws_grid_y": 60,
        "priority": "HIGH",
        "city_slug": "denver",
        # Not yet backtested — conservative regional prior
        "ensemble_models": ["ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025", "icon_seamless"],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KBOS": {
        "name": "Boston Logan",
        "market_label": "Boston",
        "icao": "KBOS",
        "resolution_unit": "F",
        "lat": 42.3656,
        "lon": -71.0096,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ma/boston/KBOS",
        "nws_grid_office": "BOX",
        "nws_grid_x": 71,
        "nws_grid_y": 90,
        "priority": "HIGH",
        "city_slug": "boston",
        "ensemble_models": ["ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025", "icon_seamless"],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KMIA": {
        "name": "Miami International",
        "market_label": "Miami",
        "icao": "KMIA",
        "resolution_unit": "F",
        "lat": 25.7959,
        "lon": -80.2870,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/fl/miami/KMIA",
        "nws_grid_office": "MFL",
        "nws_grid_x": 75,
        "nws_grid_y": 51,
        "priority": "MEDIUM",
        "city_slug": "miami",
        "ensemble_models": ["ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025", "icon_seamless"],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KSEA": {
        "name": "Seattle-Tacoma",
        "market_label": "Seattle",
        "icao": "KSEA",
        "resolution_unit": "F",
        "lat": 47.4502,
        "lon": -122.3088,
        "timezone": "America/Los_Angeles",
        "station_standard_offset_hours": -8,
        "wu_url": "https://www.wunderground.com/history/daily/us/wa/seattle/KSEA",
        "nws_grid_office": "SEW",
        "nws_grid_x": 124,
        "nws_grid_y": 67,
        "priority": "MEDIUM",
        "city_slug": "seattle",
        # Backtested: 81 days, best ensemble: ICON + GEM + NBM
        "ensemble_models": ["icon_seamless", "gem_seamless", "ncep_nbm_conus"],
        "spread_threshold": 3.0,   # °F
        "p_win_green": 0.62,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 81,
    },
    "KDFW": {
        "name": "Dallas/Fort Worth",
        "market_label": "Dallas",
        "icao": "KDFW",
        "resolution_unit": "F",
        "lat": 32.8998,
        "lon": -97.0403,
        "timezone": "America/Chicago",
        "station_standard_offset_hours": -6,
        "wu_url": "https://www.wunderground.com/history/daily/us/tx/dallas/KDFW",
        "nws_grid_office": "FWD",
        "nws_grid_x": 80,
        "nws_grid_y": 108,
        "priority": "MEDIUM",
        "city_slug": "dallas",
        "ensemble_models": ["ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025", "icon_seamless"],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "KATL": {
        "name": "Atlanta Hartsfield-Jackson",
        "market_label": "Atlanta",
        "icao": "KATL",
        "resolution_unit": "F",
        "lat": 33.6407,
        "lon": -84.4277,
        "timezone": "America/New_York",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/us/ga/atlanta/KATL",
        "nws_grid_office": "FFC",
        "nws_grid_x": 52,
        "nws_grid_y": 88,
        "priority": "MEDIUM",
        "city_slug": "atlanta",
        "ensemble_models": ["ncep_nbm_conus", "gfs_seamless", "ecmwf_ifs025", "icon_seamless"],
        "spread_threshold": 3.0,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "EGLC": {
        "name": "London City Airport",
        "market_label": "London",
        "icao": "EGLC",
        "resolution_unit": "C",
        "lat": 51.5054,
        "lon": 0.0553,
        "timezone": "Europe/London",
        "station_standard_offset_hours": 0,
        "wu_url": "https://www.wunderground.com/history/daily/gb/london/EGLC",
        "met_office_lat": 51.5054,
        "met_office_lon": 0.0553,
        "priority": "MEDIUM",
        "city_slug": "london",
        # Backtested: 75 days, 74.7% bucket accuracy. Spread signal p=0.039.
        # GREEN (≤1.0°C spread): 80.8% (42/52). RED (>1.0°C): 47.6% (10/21).
        "ensemble_models": [
            "meteofrance_arome_france",
            "meteofrance_seamless",
            "meteofrance_arome_france_hd",
            "icon_seamless",
            "dmi_seamless",
        ],
        "spread_threshold": 1.0,   # °C — pre-registered, do not change
        "p_win_green": 0.75,       # validated empirical
        "p_win_red": 0.55,         # shrunk toward base rate
        "kelly_fraction": 0.50,    # half-Kelly — 75 days of backtest IS the validation
        "backtest_n": 75,
    },
    "LFPG": {
        "name": "Paris Charles de Gaulle",
        "market_label": "Paris",
        "icao": "LFPG",
        "resolution_unit": "C",
        "lat": 49.0097,
        "lon": 2.5479,
        "timezone": "Europe/Paris",
        "station_standard_offset_hours": 1,
        "wu_url": "https://www.wunderground.com/history/daily/fr/paris/LFPG",
        "priority": "LOW",
        "city_slug": "paris",
        # Backtested: 10 days only — small sample, use conservatively
        "ensemble_models": ["ukmo_uk_deterministic_2km", "metno_seamless", "ukmo_seamless", "ecmwf_ifs025"],
        "spread_threshold": 1.5,
        "p_win_green": 0.65,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 10,
    },
    "RKSI": {
        "name": "Incheon International Airport",
        "market_label": "Seoul",
        "icao": "RKSI",
        "resolution_unit": "C",
        "lat": 37.4492,
        "lon": 126.4510,
        "timezone": "Asia/Seoul",
        "station_standard_offset_hours": 9,
        "wu_url": "https://www.wunderground.com/history/daily/kr/incheon/RKSI",
        "priority": "LOW",
        "city_slug": "seoul",
        # Backtested: ~50 days, NCEP AI-GFS + GraphCast best combination
        "ensemble_models": ["ncep_aigfs025", "gfs_graphcast025", "ecmwf_ifs025", "kma_gdps", "kma_seamless"],
        "spread_threshold": 1.5,
        "p_win_green": 0.70,
        "p_win_red": 0.55,
        "kelly_fraction": 0.35,
        "backtest_n": 50,
    },
    "SBGR": {
        "name": "Sao Paulo-Guarulhos International Airport",
        "market_label": "Sao Paulo",
        "icao": "SBGR",
        "resolution_unit": "C",
        "lat": -23.4356,
        "lon": -46.4731,
        "timezone": "America/Sao_Paulo",
        "station_standard_offset_hours": -3,
        "wu_url": "https://www.wunderground.com/history/daily/br/guarulhos/SBGR",
        "priority": "LOW",
        "city_slug": "sao-paulo",
        "ensemble_models": ["ecmwf_ifs025", "gem_global", "icon_seamless", "gfs_seamless"],
        "spread_threshold": 1.5,
        "p_win_green": 0.58,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "SAEZ": {
        "name": "Buenos Aires Ezeiza International Airport",
        "market_label": "Buenos Aires",
        "icao": "SAEZ",
        "resolution_unit": "C",
        "lat": -34.8222,
        "lon": -58.5358,
        "timezone": "America/Argentina/Buenos_Aires",
        "station_standard_offset_hours": -3,
        "wu_url": "https://www.wunderground.com/history/daily/ar/buenos-aires/SAEZ",
        "priority": "LOW",
        "city_slug": "buenos-aires",
        # Backtested: 78 days, UKMO Seamless 65.4% — UK Met Office excels in Southern Hemisphere.
        # No ensemble beats single UKMO; use ECMWF + ICON for spread signal.
        "ensemble_models": ["ukmo_seamless", "ecmwf_ifs025", "icon_seamless", "gem_global"],
        "spread_threshold": 1.5,
        "p_win_green": 0.65,
        "p_win_red": 0.55,
        "kelly_fraction": 0.30,
        "backtest_n": 78,
    },
    "NZWN": {
        "name": "Wellington International Airport",
        "market_label": "Wellington",
        "icao": "NZWN",
        "resolution_unit": "C",
        "lat": -41.3272,
        "lon": 174.8050,
        "timezone": "Pacific/Auckland",
        "station_standard_offset_hours": 12,
        "wu_url": "https://www.wunderground.com/history/daily/nz/wellington/NZWN",
        "priority": "LOW",
        "city_slug": "wellington",
        # Not yet backtested — BOM ACCESS-G best for NZ, UKMO excellent for SH.
        # Add ecmwf + icon for spread diversity.
        "ensemble_models": ["bom_access_global", "ukmo_seamless", "ecmwf_ifs025", "icon_seamless"],
        "spread_threshold": 1.5,
        "p_win_green": 0.60,
        "p_win_red": 0.52,
        "kelly_fraction": 0.25,
        "backtest_n": 0,
    },
    "LTAC": {
        "name": "Ankara Esenboğa International Airport",
        "market_label": "Ankara",
        "icao": "LTAC",
        "resolution_unit": "C",
        "lat": 40.1281,
        "lon": 32.9951,
        "timezone": "Europe/Istanbul",
        "station_standard_offset_hours": 3,
        "wu_url": "https://www.wunderground.com/history/daily/tr/%C3%A7ubuk/LTAC",
        "priority": "LOW",
        "city_slug": "ankara",
        # Backtested: 37 days, 62.2% bucket accuracy (+16.3pp over best single)
        "ensemble_models": [
            "icon_global",
            "meteofrance_arpege_world",
            "jma_seamless",
            "icon_seamless",
            "ecmwf_ifs025",
            "gfs_graphcast025",
        ],
        "spread_threshold": 1.5,
        "p_win_green": 0.70,
        "p_win_red": 0.55,
        "kelly_fraction": 0.35,
        "backtest_n": 37,
    },
    "CYYZ": {
        "name": "Toronto Pearson International Airport",
        "market_label": "Toronto",
        "icao": "CYYZ",
        "resolution_unit": "C",
        "lat": 43.6772,
        "lon": -79.6306,
        "timezone": "America/Toronto",
        "station_standard_offset_hours": -5,
        "wu_url": "https://www.wunderground.com/history/daily/ca/toronto/CYYZ",
        "priority": "LOW",
        "city_slug": "toronto",
        # Backtested: 81 days, 53.1% bucket accuracy (KMA + MF ARPEGE + GEM + DMI)
        "ensemble_models": ["kma_gdps", "meteofrance_arpege_world", "gem_global", "dmi_seamless"],
        "spread_threshold": 1.5,
        "p_win_green": 0.65,
        "p_win_red": 0.55,
        "kelly_fraction": 0.25,
        "backtest_n": 81,
    },
}


MARKET_KEYWORDS_TO_STATION = {
    "nyc": "KLGA",
    "new york city": "KLGA",
    "chicago": "KORD",
    "denver": "KDEN",
    "boston": "KBOS",
    "london": "EGLC",
    "paris": "LFPG",
    "miami": "KMIA",
    "seattle": "KSEA",
    "atlanta": "KATL",
    "dallas": "KDFW",
    "seoul": "RKSI",
    "incheon": "RKSI",
    "sao paulo": "SBGR",
    "sao-paulo": "SBGR",
    "guarulhos": "SBGR",
    "sbgr": "SBGR",
}


def find_station_for_question(question: str) -> str | None:
    lower = question.lower()
    for keyword, station in MARKET_KEYWORDS_TO_STATION.items():
        if keyword in lower:
            return station
    return None
